default: &default
  adapter: postgresql
  encoding: unicode
  database: jobportal_development
  pool: 5
  username: postgres
  password: Seedu@123

development:
  <<: *default
  host: localhost
  port: 5432

test:
  <<: *default
  database: jobportal_test
